### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in AppData\Local\Temp\pip-build-4vog3hcr\unicodecsv\

### ISSUE THREAD

**Issue by bryan-nice** [evidens/json2csv#33]
output I get from installer

Collecting unicodecsv==0.9.0 (from -r .\requirements.txt (line 1))
  Using cached unicodecsv-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bryan\AppData\Local\Temp\pip-build-4vog3hcr\unicodecsv\setup.py", line 5, in <module>
        version = **import**('unicodecsv').**version**
      File "c:\users\bryan\appdata\local\temp\pip-build-4vog3hcr\unicodecsv\unicodecsv__init__.py", line 48
        except TypeError, e:
                        ^
    SyntaxError: invalid syntax

```
----------------------------------------
```

**Comment by dhar24** [comment]
Means you're using some obsolete library in python.  This is because of invalid syntax "TypeError, e:" which doesn't support in python(3.x), can be rectified manually by replacing it by "TypeError as e". 

Quick Resolution for python 3.x: Go to requirements.txt and replace the code with 'unicodecsv' or either just install it from pip.

**Comment by jukou** [comment]
> Quick Resolution for python 3.x: Go to requirements.txt and replace the code with 'unicodecsv' or either just install it from pip.

requirements.txt only has 1 line in it.  What am I replacing exactly?
